"""empty message

Revision ID: 8c2dc98e3105
Revises: 7600f5255f11
Create Date: 2021-08-25 21:55:24.380715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c2dc98e3105'
down_revision = '7600f5255f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    op.add_column('comment', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.add_column('post', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_active')
    op.drop_column('comment', 'is_active')
    op.create_table('banner',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('link_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
