"""empty message

Revision ID: c143fec1e7c7
Revises: 8c2dc98e3105
Create Date: 2021-08-26 12:04:25.002106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c143fec1e7c7'
down_revision = '8c2dc98e3105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'is_active')
    # ### end Alembic commands ###
