"""empty message

Revision ID: cd7a9d3254a5
Revises: 47dde31b98c0
Create Date: 2021-08-23 17:55:10.915387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7a9d3254a5'
down_revision = '47dde31b98c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    # ### end Alembic commands ###
